; Generated by KLFC 1.5.6
; https://github.com/39aldo39/klfc

#MaxHotkeysPerInterval 200
#MaxThreadsPerHotkey 10

SendUps(ByRef modifiers) {
  for index, modifier in modifiers {
    if (modifier == "Caps")
      SetCapsLockState, off
    else if (modifier == "Num")
      SetNumLockState, off
    else if InStr(modifier, "Extend")
      %modifier% := false
    else
      Send {%modifier% Up}
  }
  modifiers := Object()
}

SendAsUnicode(string) {
  Result := ""
  Loop, Parse, string
    Result .= Format("{{}U+{:04x}{}}", Ord(A_LoopField))
  Send {Blind}%Result%
}

DeadKeys := ComObjCreate("Scripting.Dictionary")

DeadKey(baseChar, table, name := "") {
  Global ActiveDeadKey
  if (ActiveDeadKey != "") {
    NewActiveDeadKey := ComObjCreate("Scripting.Dictionary")
    for key in table {
      value := table.item(key)
      NewActiveDeadKey.item(key) := ActiveDeadKey.item(value)
    }
    result := ActiveDeadKey.item(name)
    if (IsObject(result)) {
      for key in result {
        value := result.item(key)
        NewActiveDeadKey.item(key) := value
      }
    } else if (result != "") {
      ActiveDeadKey := ""
      SendAsUnicode(result)
      Return
    }
    ActiveDeadKey := NewActiveDeadKey
    Return
  }
  ActiveDeadKey := table
  Input key, L1, {Esc}{F1}{F2}{F3}{F4}{F5}{F6}{F7}{F8}{F9}{F10}{F11}{F12}{Left}{Right}{Up}{Down}{Home}{End}{PgUp}{PgDn}{Del}{Ins}{BS}{PrintScreen}{Pause}{AppsKey}
  If InStr(ErrorLevel, "EndKey:") {
    ActiveDeadKey := ""
    value := SubStr(ErrorLevel, 8)
    Send {Blind}{%value%}
    SendAsUnicode(baseChar)
  } else if (ErrorLevel != "NewInput") {
    value := ActiveDeadKey.item(key)
    ActiveDeadKey := ""
    if (IsObject(value)) {
      DeadKey(baseChar, value)
    } else if (value != "") {
      SendAsUnicode(value)
    } else {
      SendAsUnicode(baseChar . key)
    }
  }
}

*SC002::Send {Blind}{VK31SC002 DownR} ; QWERTY 1: 1
*SC002 up::Send {Blind}{VK31SC002 Up}
*SC003::Send {Blind}{VK32SC003 DownR} ; QWERTY 2: 2
*SC003 up::Send {Blind}{VK32SC003 Up}
*SC004::Send {Blind}{VK33SC004 DownR} ; QWERTY 3: 3
*SC004 up::Send {Blind}{VK33SC004 Up}
*SC005::Send {Blind}{VK34SC005 DownR} ; QWERTY 4: 4
*SC005 up::Send {Blind}{VK34SC005 Up}
*SC006::Send {Blind}{VK35SC006 DownR} ; QWERTY 5: 5
*SC006 up::Send {Blind}{VK35SC006 Up}
*SC007::Send {Blind}{VK36SC007 DownR} ; QWERTY 6: 6
*SC007 up::Send {Blind}{VK36SC007 Up}
*SC008::Send {Blind}{VK37SC008 DownR} ; QWERTY 7: 7
*SC008 up::Send {Blind}{VK37SC008 Up}
*SC009::Send {Blind}{VK38SC009 DownR} ; QWERTY 8: 8
*SC009 up::Send {Blind}{VK38SC009 Up}
*SC00a::Send {Blind}{VK39SC00a DownR} ; QWERTY 9: 9
*SC00a up::Send {Blind}{VK39SC00a Up}
*SC00b::Send {Blind}{VK30SC00b DownR} ; QWERTY 0: 0
*SC00b up::Send {Blind}{VK30SC00b Up}
*SC00c::Send {Blind}{VKbdSC00c DownR} ; QWERTY -: -
*SC00c up::Send {Blind}{VKbdSC00c Up}
*SC00d::Send {Blind}{VKbbSC00d DownR} ; QWERTY +: +
*SC00d up::Send {Blind}{VKbbSC00d Up}
*SC010::Send {Blind}{VK51SC010 DownR} ; QWERTY Q: Q
*SC010 up::Send {Blind}{VK51SC010 Up}
*SC011::Send {Blind}{VK57SC011 DownR} ; QWERTY W: W
*SC011 up::Send {Blind}{VK57SC011 Up}
*SC012::Send {Blind}{VK45SC012 DownR} ; QWERTY E: E
*SC012 up::Send {Blind}{VK45SC012 Up}
*SC013::Send {Blind}{VK52SC013 DownR} ; QWERTY R: R
*SC013 up::Send {Blind}{VK52SC013 Up}
*SC014::Send {Blind}{VK54SC014 DownR} ; QWERTY T: T
*SC014 up::Send {Blind}{VK54SC014 Up}
*SC015::Send {Blind}{VK59SC015 DownR} ; QWERTY Y: Y
*SC015 up::Send {Blind}{VK59SC015 Up}
*SC016::Send {Blind}{VK55SC016 DownR} ; QWERTY U: U
*SC016 up::Send {Blind}{VK55SC016 Up}
*SC017::Send {Blind}{VK49SC017 DownR} ; QWERTY I: I
*SC017 up::Send {Blind}{VK49SC017 Up}
*SC018::Send {Blind}{VK4fSC018 DownR} ; QWERTY O: O
*SC018 up::Send {Blind}{VK4fSC018 Up}
*SC019::Send {Blind}{VK50SC019 DownR} ; QWERTY P: P
*SC019 up::Send {Blind}{VK50SC019 Up}
*SC01a::Send {Blind}{VKdbSC01a DownR} ; QWERTY [: [
*SC01a up::Send {Blind}{VKdbSC01a Up}
*SC01b::Send {Blind}{VKddSC01b DownR} ; QWERTY ]: ]
*SC01b up::Send {Blind}{VKddSC01b Up}
*SC01e::Send {Blind}{VK41SC01e DownR} ; QWERTY A: A
*SC01e up::Send {Blind}{VK41SC01e Up}
*SC01f::Send {Blind}{VK53SC01f DownR} ; QWERTY S: S
*SC01f up::Send {Blind}{VK53SC01f Up}
*SC020::Send {Blind}{VK44SC020 DownR} ; QWERTY D: D
*SC020 up::Send {Blind}{VK44SC020 Up}
*SC021::Send {Blind}{VK46SC021 DownR} ; QWERTY F: F
*SC021 up::Send {Blind}{VK46SC021 Up}
*SC022::Send {Blind}{VK47SC022 DownR} ; QWERTY G: G
*SC022 up::Send {Blind}{VK47SC022 Up}
*SC023::Send {Blind}{VK48SC023 DownR} ; QWERTY H: H
*SC023 up::Send {Blind}{VK48SC023 Up}
*SC024::Send {Blind}{VK4aSC024 DownR} ; QWERTY J: J
*SC024 up::Send {Blind}{VK4aSC024 Up}
*SC025::Send {Blind}{VK4bSC025 DownR} ; QWERTY K: K
*SC025 up::Send {Blind}{VK4bSC025 Up}
*SC026::Send {Blind}{VK4cSC026 DownR} ; QWERTY L: L
*SC026 up::Send {Blind}{VK4cSC026 Up}
*SC027::Send {Blind}{VKbaSC027 DownR} ; QWERTY ;: ;
*SC027 up::Send {Blind}{VKbaSC027 Up}
*SC028::Send {Blind}{VKdeSC028 DownR} ; QWERTY ': '
*SC028 up::Send {Blind}{VKdeSC028 Up}
*SC029::Send {Blind}{VKc0SC029 DownR} ; QWERTY ~: ~
*SC029 up::Send {Blind}{VKc0SC029 Up}
*SC02b::Send {Blind}{VKdcSC02b DownR} ; QWERTY \: \
*SC02b up::Send {Blind}{VKdcSC02b Up}
*SC02c::Send {Blind}{VK5aSC02c DownR} ; QWERTY Z: Z
*SC02c up::Send {Blind}{VK5aSC02c Up}
*SC02d::Send {Blind}{VK58SC02d DownR} ; QWERTY X: X
*SC02d up::Send {Blind}{VK58SC02d Up}
*SC02e::Send {Blind}{VK43SC02e DownR} ; QWERTY C: C
*SC02e up::Send {Blind}{VK43SC02e Up}
*SC02f::Send {Blind}{VK56SC02f DownR} ; QWERTY V: V
*SC02f up::Send {Blind}{VK56SC02f Up}
*SC030::Send {Blind}{VK42SC030 DownR} ; QWERTY B: B
*SC030 up::Send {Blind}{VK42SC030 Up}
*SC031::Send {Blind}{VK4eSC031 DownR} ; QWERTY N: N
*SC031 up::Send {Blind}{VK4eSC031 Up}
*SC032::Send {Blind}{VK4dSC032 DownR} ; QWERTY M: M
*SC032 up::Send {Blind}{VK4dSC032 Up}
*SC033::Send {Blind}{VKbcSC033 DownR} ; QWERTY ,: ,
*SC033 up::Send {Blind}{VKbcSC033 Up}
*SC034::Send {Blind}{VKbeSC034 DownR} ; QWERTY .: .
*SC034 up::Send {Blind}{VKbeSC034 Up}
*SC035::Send {Blind}{VKbfSC035 DownR} ; QWERTY /: /
*SC035 up::Send {Blind}{VKbfSC035 Up}
*SC039::Send {Blind}{VK20SC039 DownR} ; QWERTY Space: Space
*SC039 up::Send {Blind}{VK20SC039 Up}
*SC056::Send {Blind}{VKe2SC056 DownR} ; QWERTY Iso: Iso
*SC056 up::Send {Blind}{VKe2SC056 Up}
*SC053::Send {Blind}{VK6eSC053 DownR} ; QWERTY KP_Dec: KP_Dec
*SC053 up::Send {Blind}{VK6eSC053 Up}

; QWERTY 1
#if
SC002::Send {Blind}{U+0031} ; 1
+SC002::Send {Blind}{U+0021} ; !
^SC002::Return
!^SC002::Return
+!^SC002::Return

; QWERTY 2
#if
SC003::Send {Blind}{U+0032} ; 2
+SC003::Send {Blind}{U+0040} ; @
^SC003::Return
!^SC003::Return
+!^SC003::Return

; QWERTY 3
#if
SC004::Send {Blind}{U+0033} ; 3
+SC004::Send {Blind}{U+0023} ; #
^SC004::Return
!^SC004::Send {Blind}{U+20ac} ; €
+!^SC004::Return

; QWERTY 4
#if
SC005::Send {Blind}{U+0034} ; 4
+SC005::Send {Blind}{U+0024} ; $
^SC005::Return
!^SC005::Send {Blind}{U+20aa} ; ₪
+!^SC005::Return

; QWERTY 5
#if
SC006::Send {Blind}{U+0035} ; 5
+SC006::Send {Blind}{U+0025} ; %
^SC006::Return
!^SC006::Send {Blind}{U+00b0} ; °
+!^SC006::Return

; QWERTY 6
#if
SC007::Send {Blind}{U+0036} ; 6
+SC007::Send {Blind}{U+005e} ; ^
^SC007::Return
!^SC007::Return
+!^SC007::Return

; QWERTY 7
#if
SC008::Send {Blind}{U+0037} ; 7
+SC008::Send {Blind}{U+0026} ; &
^SC008::Return
!^SC008::Return
+!^SC008::Return

; QWERTY 8
#if
SC009::Send {Blind}{U+0038} ; 8
+SC009::Send {Blind}{U+002a} ; *
^SC009::Return
!^SC009::Send {Blind}{U+00d7} ; ×
+!^SC009::Return

; QWERTY 9
#if
SC00a::Send {Blind}{U+0039} ; 9
+SC00a::Send {Blind}{U+0028} ; (
^SC00a::Return
!^SC00a::Return
+!^SC00a::Return

; QWERTY 0
#if
SC00b::Send {Blind}{U+0030} ; 0
+SC00b::Send {Blind}{U+0029} ; )
^SC00b::Return
!^SC00b::Return
+!^SC00b::Return

; QWERTY -
#if
SC00c::Send {Blind}{U+002d} ; -
+SC00c::Send {Blind}{U+005f} ; _
^SC00c::Return
!^SC00c::Send {Blind}{U+200c} ; ‌
+!^SC00c::Return

; QWERTY +
#if
SC00d::Send {Blind}{U+003d} ; =
+SC00d::Send {Blind}{U+002b} ; +
^SC00d::Return
!^SC00d::Send {Blind}{U+200d} ; ‍
+!^SC00d::Return

; QWERTY Q
#if
SC010::Send {Blind}{U+05e7} ; ק
+SC010::Return
^SC010::Return
!^SC010::Send {Blind}{U+05b8} ; ָ
+!^SC010::Send {Blind}{U+05c7} ; ׇ

; QWERTY W
#if
SC011::Send {Blind}{U+05e9} ; ש
+SC011::Send {Blind}{U+05e1} ; ס
^SC011::Return
!^SC011::Send {Blind}{U+05e9}{U+05c1} ; שׁ
+!^SC011::Send {Blind}{U+05e9}{U+05c2} ; שׂ

; QWERTY E
#if
SC012::Send {Blind}{U+05e2} ; ע
+SC012::Send {Blind}{U+05d0} ; א
^SC012::Return
!^SC012::Send {Blind}{U+05b6} ; ֶ
+!^SC012::Send {Blind}{U+05b5} ; ֵ

; QWERTY R
#if
SC013::Send {Blind}{U+05e8} ; ר
+SC013::Return
^SC013::Return
!^SC013::Return
+!^SC013::Return

; QWERTY T
#if
SC014::Send {Blind}{U+05ea} ; ת
+SC014::Send {Blind}{U+05d8} ; ט
^SC014::Return
!^SC014::Send {Blind}{U+05ea}{U+05bc} ; תּ
+!^SC014::Return

; QWERTY Y
#if
SC015::Send {Blind}{U+05d9} ; י
+SC015::Return
^SC015::Return
!^SC015::Send {Blind}{U+05b5} ; ֵ
+!^SC015::Return

; QWERTY U
#if
SC016::Send {Blind}{U+05d5} ; ו
+SC016::Send {Blind}{U+05d5}{U+05bc} ; וּ
^SC016::Return
!^SC016::Send {Blind}{U+05bb} ; ֻ
+!^SC016::Return

; QWERTY I
#if
SC017::Send {Blind}{U+05d9} ; י
+SC017::Return
^SC017::Return
!^SC017::Send {Blind}{U+05b4} ; ִ
+!^SC017::Return

; QWERTY O
#if
SC018::Send {Blind}{U+05d5} ; ו
+SC018::Send {Blind}{U+05d5}{U+05b9} ; וֹ
^SC018::Return
!^SC018::Send {Blind}{U+05b9} ; ֹ
+!^SC018::Send {Blind}{U+05c7} ; ׇ

; QWERTY P
#if
SC019::Send {Blind}{U+05e4} ; פ
+SC019::Send {Blind}{U+05e3} ; ף
^SC019::Return
!^SC019::Send {Blind}{U+05e4}{U+05bc} ; פּ
+!^SC019::Send {Blind}{U+05e3}{U+05bc} ; ףּ

; QWERTY [
#if
SC01a::Send {Blind}{U+005b} ; [
+SC01a::Send {Blind}{U+007b} ; {
^SC01a::Return
!^SC01a::Send {Blind}{U+200e} ; ‎
+!^SC01a::Return

; QWERTY ]
#if
SC01b::Send {Blind}{U+005d} ; ]
+SC01b::Send {Blind}{U+007d} ; }
^SC01b::Return
!^SC01b::Send {Blind}{U+200f} ; ‏
+!^SC01b::Return

; QWERTY A
#if
SC01e::Send {Blind}{U+05d0} ; א
+SC01e::Send {Blind}{U+05e2} ; ע
^SC01e::Return
!^SC01e::Send {Blind}{U+05b7} ; ַ
+!^SC01e::Send {Blind}{U+05b8} ; ָ

; QWERTY S
#if
SC01f::Send {Blind}{U+05e1} ; ס
+SC01f::Send {Blind}{U+05e9} ; ש
^SC01f::Return
!^SC01f::Return
+!^SC01f::Return

; QWERTY D
#if
SC020::Send {Blind}{U+05d3} ; ד
+SC020::Return
^SC020::Return
!^SC020::Return
+!^SC020::Return

; QWERTY F
#if
SC021::Send {Blind}{U+05e4} ; פ
+SC021::Send {Blind}{U+05e3} ; ף
^SC021::Return
!^SC021::Send {Blind}{U+05e4}{U+05bc} ; פּ
+!^SC021::Send {Blind}{U+05e3}{U+05bc} ; ףּ

; QWERTY G
#if
SC022::Send {Blind}{U+05d2} ; ג
+SC022::Return
^SC022::Return
!^SC022::Return
+!^SC022::Return

; QWERTY H
#if
SC023::Send {Blind}{U+05d4} ; ה
+SC023::Return
^SC023::Return
!^SC023::Return
+!^SC023::Return

; QWERTY J
#if
SC024::Send {Blind}{U+05d8} ; ט
+SC024::Send {Blind}{U+05ea} ; ת
^SC024::Return
!^SC024::Return
+!^SC024::Return

; QWERTY K
#if
SC025::Send {Blind}{U+05db} ; כ
+SC025::Send {Blind}{U+05da} ; ך
^SC025::Return
!^SC025::Send {Blind}{U+05db}{U+05bc} ; כּ
+!^SC025::Send {Blind}{U+05da}{U+05bc} ; ךּ

; QWERTY L
#if
SC026::Send {Blind}{U+05dc} ; ל
+SC026::Return
^SC026::Return
!^SC026::Return
+!^SC026::Return

; QWERTY ;
#if
SC027::Send {Blind}{U+003b} ; ;
+SC027::Send {Blind}{U+003a} ; :
^SC027::Return
!^SC027::Return
+!^SC027::Return

; QWERTY '
#if
SC028::Send {Blind}{U+0027} ; '
+SC028::Send {Blind}{U+0022} ; "
^SC028::Return
!^SC028::Send {Blind}{U+05b0} ; ְ
+!^SC028::
; ְ
if (DeadKeys.item("ְ") == "") {
  DeadKeys.item("ְ") := ComObjCreate("Scripting.Dictionary")
}
DeadKey("ְ", DeadKeys.item("ְ"), "cdk:ְ")
Return

; QWERTY ~
#if
SC029::Send {Blind}{U+0060} ; `
+SC029::Send {Blind}{U+007e} ; ~
^SC029::Return
!^SC029::Return
+!^SC029::Return

; QWERTY \
#if
SC02b::Send {Blind}{U+005c} ; \
+SC02b::Send {Blind}{U+007c} ; |
^SC02b::Return
!^SC02b::Return
+!^SC02b::Return

; QWERTY Z
#if
SC02c::Send {Blind}{U+05d6} ; ז
+SC02c::Return
^SC02c::Return
!^SC02c::Return
+!^SC02c::Return

; QWERTY X
#if
SC02d::Send {Blind}{U+05d7} ; ח
+SC02d::Return
^SC02d::Return
!^SC02d::Return
+!^SC02d::Return

; QWERTY C
#if
SC02e::Send {Blind}{U+05e6} ; צ
+SC02e::Send {Blind}{U+05e5} ; ץ
^SC02e::Return
!^SC02e::Return
+!^SC02e::Return

; QWERTY V
#if
SC02f::Send {Blind}{U+05d5} ; ו
+SC02f::Return
^SC02f::Return
!^SC02f::Return
+!^SC02f::Return

; QWERTY B
#if
SC030::Send {Blind}{U+05d1} ; ב
+SC030::Return
^SC030::Return
!^SC030::Send {Blind}{U+05d1}{U+05bc} ; בּ
+!^SC030::Return

; QWERTY N
#if
SC031::Send {Blind}{U+05e0} ; נ
+SC031::Send {Blind}{U+05df} ; ן
^SC031::Return
!^SC031::Return
+!^SC031::Return

; QWERTY M
#if
SC032::Send {Blind}{U+05de} ; מ
+SC032::Send {Blind}{U+05dd} ; ם
^SC032::Return
!^SC032::Return
+!^SC032::Return

; QWERTY ,
#if
SC033::Send {Blind}{U+002c} ; ,
+SC033::Send {Blind}{U+003c} ; <
^SC033::Return
!^SC033::Return
+!^SC033::Return

; QWERTY .
#if
SC034::Send {Blind}{U+002e} ; .
+SC034::Send {Blind}{U+003e} ; >
^SC034::Return
!^SC034::Send {Blind}{U+05bc} ; ּ
+!^SC034::Return

; QWERTY /
#if
SC035::Send {Blind}{U+002f} ; /
+SC035::Send {Blind}{U+003f} ; ?
^SC035::Return
!^SC035::Send {Blind}{U+00f7} ; ÷
+!^SC035::Return

; QWERTY Space
#if
SC039::Send {Blind}{U+0020} ;  
+SC039::Send {Blind}{U+0020} ;  
^SC039::Return
!^SC039::Return
+!^SC039::Return

; QWERTY Iso
#if
SC056::Send {Blind}{U+005c} ; \
+SC056::Send {Blind}{U+007c} ; |
^SC056::Return
!^SC056::Return
+!^SC056::Return

; QWERTY KP_Dec
#if
SC053::Send {Blind}{U+002e} ; .
+SC053::Send {Blind}{U+002e} ; .
^SC053::Return
!^SC053::Return
+!^SC053::Return
